### ISSUE TITLE
Add Haskell plugin logo

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo-haskell#6]
Logo from Wikipedia: https://en.wikipedia.org/wiki/Haskell_(programming_language)#/media/File:Logo_of_the_Haskell_programming_language.svg
![изображение](https://user-images.githubusercontent.com/16825982/139639593-0441c7df-88e7-4423-a670-6e247ce099de.png)

**Comment by VISTALL** [comment]
Hello. Thanks for logo, but next time - please attach square icon in svg without name(only logo)
